
init -1:


    image ss sad casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'))

    image ss scared casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'))

    image ss cry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'))

    image ss shy casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'))

    image ss nosmile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'))

    image ss cry2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'))

    image ss shy2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'))

    image ss normal casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'))

    image ss crysmile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'))

    image ss crysmile2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'))

    image ss unsure casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'))

    image ss surprise casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'))


    image ss grin casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'))

    image ss grin_smile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'))

    image ss laugh casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'))


    image ss smile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'))

    image ss smile2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'))

    image ss angry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'))

    image ss vangry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'))

    image ss serious casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'))




    image ss sad fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'))

    image ss scared fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'))

    image ss cry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'))

    image ss shy fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'))

    image ss nosmile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'))

    image ss cry2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'))

    image ss shy2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'))

    image ss normal fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'))

    image ss crysmile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'))

    image ss crysmile2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'))

    image ss unsure fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'))

    image ss surprise fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'))


    image ca grin fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'))

    image ca grin_smile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'))

    image ca laugh fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'))


    image ca smile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'))

    image ca smile2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'))

    image ca vangry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'))

    image ca angry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'))

    image ca serious fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'))


    image ca sad casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'))

    image ca scared casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'))

    image ca cry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'))

    image ca shy casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'))

    image ca nosmile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'))

    image ca cry2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'))

    image ca shy2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'))

    image ca normal casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'))

    image ca crysmile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'))

    image ca crysmile2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'))

    image ca unsure casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'))

    image ca surprise casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_casual.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'))


    image ca grin casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'))

    image ca grin_smile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'))

    image ca laugh casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_casual.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'))


    image ca smile casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'))

    image ca smile2 casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'))

    image ca angry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'))

    image ca vangry casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'))

    image ca serious casual = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_casual.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'))




    image ca sad fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-sad.png'))

    image ca scared fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-scared.png'))

    image ca cry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cry.png'))

    image ca shy fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy.png'))

    image ca nosmile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-nosmile.png'))

    image ca cry2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-cryhard.png'))

    image ca shy2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-shy2.png'))

    image ca normal fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-normal.png'))

    image ca crysmile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile.png'))

    image ca crysmile2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-crysmile2.png'))

    image ca unsure fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-unsure.png'))

    image ca surprise fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_1_fancy.png', (0, 0), 'mods/mylist/image/sprites/1-surprise.png'))


    image ca grin fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin.png'))

    image ca grin_smile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-grin_smile.png'))

    image ca laugh fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_2_fancy.png', (0, 0), 'mods/mylist/image/sprites/2-laugh.png'))


    image ca smile fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile.png'))

    image ca smile2 fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-smile2.png'))

    image ca vangry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-vangry.png'))

    image ca angry fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-angry.png'))

    image ca serious fancy = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((540, 1080), (0, 0), 'mods/mylist/image/sprites/ss_3_fancy.png', (0, 0), 'mods/mylist/image/sprites/3-serious.png'))
